export default {
	appId: '',
	appKey: '',
	cubeToken: '',
	userList: [],
	groupList:[],
	allUserList: [],
	inviteList: [],
	curUser: '',
	curGroup: '',
	messagePeer: '',
	showCLocalVideo: false,
	showCRemoteVideo: false,
	showBellAudio: false,
	showLocalCanvas: false,
	showWBCanvas: false,
	showLocalVideo: false,
	showRemoteVideo: false,
	shareVideo: false,
	groupVideo: '',
	audioCall: '',
	whiteboard: '',
	shareScreen: '',
	inviteType: '',
	inviteTypeInComing: '',
	groupFace:"./../assets/img/group-face.jpg",
	userFace:"./../assets/img/user-face.jpg",
	leftHoverNav:'0',
	joinedList: [],
	allUnread:0,
	loadingMsg: null,
	messageBottomFixed:true,
}
